# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/shayan/data/cpp/firestorm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/shayan/data/cpp/firestorm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shayan/data/cpp/firestorm/CMakeFiles /home/shayan/data/cpp/firestorm//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shayan/data/cpp/firestorm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named firestorm

# Build rule for target.
firestorm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 firestorm
.PHONY : firestorm

# fast build rule for target.
firestorm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firestorm.dir/build.make CMakeFiles/firestorm.dir/build
.PHONY : firestorm/fast

src/fsm.o: src/fsm.cpp.o

.PHONY : src/fsm.o

# target to build an object file
src/fsm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firestorm.dir/build.make CMakeFiles/firestorm.dir/src/fsm.cpp.o
.PHONY : src/fsm.cpp.o

src/fsm.i: src/fsm.cpp.i

.PHONY : src/fsm.i

# target to preprocess a source file
src/fsm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firestorm.dir/build.make CMakeFiles/firestorm.dir/src/fsm.cpp.i
.PHONY : src/fsm.cpp.i

src/fsm.s: src/fsm.cpp.s

.PHONY : src/fsm.s

# target to generate assembly for a file
src/fsm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firestorm.dir/build.make CMakeFiles/firestorm.dir/src/fsm.cpp.s
.PHONY : src/fsm.cpp.s

src/loadconfig.o: src/loadconfig.cpp.o

.PHONY : src/loadconfig.o

# target to build an object file
src/loadconfig.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firestorm.dir/build.make CMakeFiles/firestorm.dir/src/loadconfig.cpp.o
.PHONY : src/loadconfig.cpp.o

src/loadconfig.i: src/loadconfig.cpp.i

.PHONY : src/loadconfig.i

# target to preprocess a source file
src/loadconfig.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firestorm.dir/build.make CMakeFiles/firestorm.dir/src/loadconfig.cpp.i
.PHONY : src/loadconfig.cpp.i

src/loadconfig.s: src/loadconfig.cpp.s

.PHONY : src/loadconfig.s

# target to generate assembly for a file
src/loadconfig.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firestorm.dir/build.make CMakeFiles/firestorm.dir/src/loadconfig.cpp.s
.PHONY : src/loadconfig.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firestorm.dir/build.make CMakeFiles/firestorm.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firestorm.dir/build.make CMakeFiles/firestorm.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firestorm.dir/build.make CMakeFiles/firestorm.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/ply.o: src/ply.cpp.o

.PHONY : src/ply.o

# target to build an object file
src/ply.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firestorm.dir/build.make CMakeFiles/firestorm.dir/src/ply.cpp.o
.PHONY : src/ply.cpp.o

src/ply.i: src/ply.cpp.i

.PHONY : src/ply.i

# target to preprocess a source file
src/ply.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firestorm.dir/build.make CMakeFiles/firestorm.dir/src/ply.cpp.i
.PHONY : src/ply.cpp.i

src/ply.s: src/ply.cpp.s

.PHONY : src/ply.s

# target to generate assembly for a file
src/ply.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firestorm.dir/build.make CMakeFiles/firestorm.dir/src/ply.cpp.s
.PHONY : src/ply.cpp.s

src/uttype.o: src/uttype.cpp.o

.PHONY : src/uttype.o

# target to build an object file
src/uttype.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firestorm.dir/build.make CMakeFiles/firestorm.dir/src/uttype.cpp.o
.PHONY : src/uttype.cpp.o

src/uttype.i: src/uttype.cpp.i

.PHONY : src/uttype.i

# target to preprocess a source file
src/uttype.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firestorm.dir/build.make CMakeFiles/firestorm.dir/src/uttype.cpp.i
.PHONY : src/uttype.cpp.i

src/uttype.s: src/uttype.cpp.s

.PHONY : src/uttype.s

# target to generate assembly for a file
src/uttype.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firestorm.dir/build.make CMakeFiles/firestorm.dir/src/uttype.cpp.s
.PHONY : src/uttype.cpp.s

src/wavefront.o: src/wavefront.cpp.o

.PHONY : src/wavefront.o

# target to build an object file
src/wavefront.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firestorm.dir/build.make CMakeFiles/firestorm.dir/src/wavefront.cpp.o
.PHONY : src/wavefront.cpp.o

src/wavefront.i: src/wavefront.cpp.i

.PHONY : src/wavefront.i

# target to preprocess a source file
src/wavefront.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firestorm.dir/build.make CMakeFiles/firestorm.dir/src/wavefront.cpp.i
.PHONY : src/wavefront.cpp.i

src/wavefront.s: src/wavefront.cpp.s

.PHONY : src/wavefront.s

# target to generate assembly for a file
src/wavefront.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firestorm.dir/build.make CMakeFiles/firestorm.dir/src/wavefront.cpp.s
.PHONY : src/wavefront.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... firestorm"
	@echo "... src/fsm.o"
	@echo "... src/fsm.i"
	@echo "... src/fsm.s"
	@echo "... src/loadconfig.o"
	@echo "... src/loadconfig.i"
	@echo "... src/loadconfig.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/ply.o"
	@echo "... src/ply.i"
	@echo "... src/ply.s"
	@echo "... src/uttype.o"
	@echo "... src/uttype.i"
	@echo "... src/uttype.s"
	@echo "... src/wavefront.o"
	@echo "... src/wavefront.i"
	@echo "... src/wavefront.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

